# Generated by Django 3.1.7 on 2021-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
