# Generated by Django 3.1.7 on 2021-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
