# Generated by Django 3.1.7 on 2021-08-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210807_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='door_number',
        ),
    ]
