# Generated by Django 3.1.7 on 2021-08-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_door_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
    ]
